controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster
    
    effort_controller:
        type: effort_controllers/JointGroupEffortController
  

joint_state_broadcaster:
  ros__parameters:
    joints:
      - motor_joint

effort_controller:
  ros__parameters:
    joints:
      - motor_joint